### ISSUE TITLE
New upstream version 4.3.2

### ISSUE THREAD

**Issue by jooola** [raoulbhatia/backuppc#10]
Hello @raoulbhatia 

Would you have some time left to update your repository with upstream ? Debian packaging is something completely unknown to me, but I could give it a try if you think its for the best ?

https://github.com/backuppc/backuppc/releases/tag/4.3.2

Cheers, :beers:

**Comment by raoulbhatia** [comment]
Hi @jooola, thanks for reminding me.

I was quite busy with work and family and forgot to check out the new release.


I've merged the 4.3.2 tag myself and only then saw your pull request #11.  Again, sorry about that.
I didn't check the detailed diff but at first glance it seems that I merged tag 4.3.2 whilst you merged the master branch.  Are there any specific bugfixes in master that you think should be included in 4.3.2?

Lastly, as I am still on Ubuntu 18.04 LTS on my backup server, I built a package and published them at https://github.com/backuppc/backuppc/wiki/Build-Your-Own-Packages#ubuntu-1804-lts-bionic-beaver

**Comment by jooola** [comment]
@raoulbhatia I did merged from master, it was a mistake. We should probably stick to 4.3.2 even if everything is running fine on my side.

Let me close the PR I made, I don't mind.

I build my own packages on debian buster, and haven't noticed any problem. But my setup is really simple, I only use rsyncd for transfer so I might not give a proper answer whether it works properly on debian.

**Comment by jooola** [comment]
Feel free to close this when you think it's done. Thanks for this quick update !

**Comment by raoulbhatia** [comment]
Closed via 40a4c0095a580a4768b7e41da3074d887c70982d and b1bbdd5148225237f963fe32058cd9e2c75feaf6
