### ISSUE TITLE
Debian build is breaking when user backuppc is not present

### ISSUE THREAD

**Issue by raoulbhatia** [raoulbhatia/backuppc#5]
@brenard's 0260c46 commit is just a workaround for Debian building package process on host without `backuppc` user.

By setting while(0), I disable the following while block that try to determine `backuppc` user infos, which fail on host without `backuppc` user. I first try to use `--no-set-perms` parameter of configure.pl script in `debian/rules` file but it's not working.

This workaround could certainly be fixed be using a more graceful solution but it's currently the easier way for me.

I will try to see if the `--no-set-perms` parameter could be a proper solution by fixing it effect in configure.pl file. In this case, I could propose a PR upstream for that and we could use it to fix this problem by just using `--no-set-perms parameter` in `debian/rules` file, like I first tried.

**Comment by rhansen** [comment]
Passing `--no-set-perms` worked for me. See PR #13 and [PPA build log](https://launchpadlibrarian.net/484852047/buildlog_ubuntu-bionic-amd64.backuppc_4.3.2~ubuntu18.04.1~ppa2_BUILDING.txt.gz).

**Comment by raoulbhatia** [comment]
I verified this on Debian Buster.  Thanks & Closing!
